version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        container_name: 'app'
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8081:80"
            - '${VITE_PORT:-5173}:5173'
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
          - 'laraveldb:/var/lib/mysql'
        ports:
            - "3388:3306"
        networks:
            - laravel
    npm:
        tty: true
        image: node:20-alpine
        container_name: npm
        volumes:
            - ./:/var/www/app
        working_dir: /var/www/app
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    laraveldb:
        driver: local