version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        container_name: 'app'
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - '${FORWARD_APP_PORT:-8081}:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    mariadb:
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'laraveldb:/var/lib/mysql'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    node:
        tty: true
        image: node:20-alpine
        container_name: node
        volumes:
            - ./:/var/www/app
        working_dir: /var/www/app
        ports:
            - "5173:5173"
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    laraveldb:
        driver: local